services:
  - type: web
    name: anime-opening-quiz
    env: node
    plan: free
    buildCommand: yarn
    startCommand: node server.js
    envVars:
      - key: DATA_DIR
        value: /var/data
      - key: MODERATOR_PASSWORD
        value: Kochamkotki
    disk:
      name: anime-opening-quiz-data
      mountPath: /var/data
      sizeGB: 1
