services:
  - type: web
    name: muzyczne-lobby
    env: node
    plan: free
    buildCommand: yarn
    startCommand: node server.js
    envVars:
      - key: DATA_DIR
        value: /var/data
    disk:
      name: muzyczne-lobby-data
      mountPath: /var/data
      sizeGB: 1
